### PR TITLE
Materialize location list designs

### PR DESCRIPTION
**Pull request by AndyScherzinger**
materialized the list item design based on https://material.io/guidelines/components/lists.html#lists-specs

**Before:**
favs_old

one_result_old

multi_result_old

cc for comments: @rskikuli @sidorelauku @AnXh3L0

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
As per discussion with Elio I'll create some screenshots with a smaller icon size, likely tomorrow.

**Comment by AndyScherzinger** [comment]
Status Quo:
device-2018-03-01-155417
device-2018-03-01-155255

**Comment by AndyScherzinger** [comment]
Status Quo:
device-2018-03-01-165836
device-2018-03-01-165658

**Comment by rskikuli** [comment]
@AnXh3L0 can you please make a quick review and approve? Thank you guys!

**Comment by rskikuli** [comment]
The design looks fine from my side!

**Comment by AndyScherzinger** [comment]
optimized the divider design according to Elio's feedback
device-2018-03-03-155632
device-2018-03-03-155211

**Pull request merged**
